# Generated by Django 6.1 on 2026-08-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienvenida', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
